<a href="https://colab.research.google.com/github/izza1234567859/PM-4404/blob/main/categorialEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import pandas as pd
df = pd.DataFrame({
    'country':['India', 'US', 'Japan', 'US', 'Japan'],
    'age': [44,34,46,35,23],
    'salary':[72000, 65000, 98000, 45000,34000]
})
df

  country  age  salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

In [4]:
# Label encoding pada Scikit learn #
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['country'] = label_encoder.fit_transform(df['country'])
df

   country  age  salary
0        0   44   72000
1        2   34   65000
2        1   46   98000
3        2   35   45000
4        1   23   34000

In [5]:
# Cara memahami bagaimana atribut *country* berubah dari kategori (teks) menjadi numerik (number) #

label_encoder.classes_

array(['India', 'Japan', 'US'], dtype=object)

In [6]:
# Dataset #

import pandas as pd
df = pd.DataFrame({
    'country':['India', 'US', 'Japan', 'US', 'Japan'],
    'age': [44,34,46,35,23],
    'salary':[72000, 65000, 98000, 45000,34000]
})
df

  country  age  salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

In [7]:
X = df['country'].values.reshape(-1,1)
X

array([['India'],
       ['US'],
       ['Japan'],
       ['US'],
       ['Japan']], dtype=object)

In [8]:
# One-hot encoding pada Scikit learn #

from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
X = onehot_encoder.fit_transform(X).toarray()
X

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [9]:
#utk memahami proses di atas kita tulis sintak#
onehot_encoder.categories_

[array(['India', 'Japan', 'US'], dtype=object)]

In [10]:
df_onehot= pd.DataFrame(X, columns=[str(i) for i in range(X.shape[1])])
df_onehot

     0    1    2
0  1.0  0.0  0.0
1  0.0  0.0  1.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0

In [11]:
# karena atribut 'country' sudah direpresentasikan dengan OneHotEncoder maka kita buang#

df = df.drop(['country'], axis=1)
df

   age  salary
0   44   72000
1   34   65000
2   46   98000
3   35   45000
4   23   34000